#!/usr/bin/python

# 28 May 2019 - gswann
# connects to lightning manager to get pertinent lightning data
# may make decision to shutdown this system

#from time import sleep

# version 1.1 - 12 Jun 2019 - gswann
# will shutdown itself when LD says 100%

# version 1.2 - 13 Jul 2019 - gswann
# prints myURL into logfile

# version 1.3 14 Jul 2019 - gswann
# accesses ups at startup for testing

# version 1.4 15 jul 2019 - gswann
# use MQTT publish to xmit return code to HA server
# adding try block around curl

from __future__ import print_function
import time
from datetime import datetime
import socket
from subprocess import check_call
import paho.mqtt.publish as publish

version = "1.4"

# which mode do we use?
# 0 = real port, real cmd
# 1 = test port, real cmd
# 2 = test port, test cmd 

testmode = 0

if testmode > 0:
   print("starting test port mode...")
   testport = 1
else:
   testport = 0
    
if testmode == 2:
    print("starting test cmd mode...")
    upsCmd = 'pause'
else:
    print("starting real cmd mode...")
    upsCmd = 'stop'


myHost = socket.gethostname()
# create map from hostname to supporting UPS
map = {'rp6':'ota7',
       'rp5':'ota5',
       'zero4':'ota6'}
upsHost = (map[myHost])
myURL = 'http://ups-control-' + upsHost + './' + upsCmd
myURLtest = 'http://ups-control-' + upsHost + './'

retcode = 99
print("Version " + version)
print('running on host ' + myHost + ' supported by ' + upsHost)
print('with command URL ' + myURL)
# print(myURL)

print('')
strikes = 0
oldStrikes = 0
prob = -1
oldProb = -1
mySleep = 2

def checkUPS():
   global myURLtest, retcode
   print("\n*********************")
   try:
      retcode = check_call(['/usr/bin/curl', myURLtest])
   except:
      publish.single(myHost + "/retcode",retcode, hostname = "ha32163", auth={'username':"hass", 'password':"hass"})
   print("*********************\n")

def checkin():
    global mySleep,oldStrikes,strikes,delta,samecnt,oldProb,prob
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    host = 'zero5'
    if testport == 0:
       port = 4700
    else:
       port = 4701
    s.settimeout(5.0)

    try:
       s.connect((host, port))
    except:
          print('couldnt connect')
          prob = -1
#          time.sleep(10)
#          s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
       # Receive no more than 1024 bytes

    else:    
       s.sendall(b'status')
       msg = s.recv(1024)
       s.close()
       hdr,strikes,delta,samecnt,prob = msg.split(" ")
       strikes = int(strikes)
       delta = int(delta)
       prob = int(prob)
       print (hdr,strikes,delta,samecnt,prob, end=' - ') 

       if (strikes != oldStrikes) or (prob != oldProb):
          mySleep = 2
          oldStrikes = strikes
          oldProb = prob
       else:
          mySleep += 4
          if mySleep > 30:
            mySleep = 30

#       print strikes
#       print (msg.decode('ascii'))

# if the very first prob is 100, wait until it isn't
# we don't want to reboot after an hour and immediately shutdown again.
# I think...

# prob = 100

print("Checking for good startup value")
while (prob == 100 or prob == -1):
   checkUPS()
   checkin()

   if (prob == 100 or prob == -1):
      print("Waiting for good startup value")
      time.sleep(30)

#checkUPS()
print("OK to start up")
publish.single(myHost + "/retcode",retcode, hostname = "ha32163", auth={'username':"hass", 'password':"hass"})

myTime = time.time() + 120

while 1:
        if myTime < time.time():
           checkUPS()
           myTime = time.time() + 120

	checkin()

	if prob == 0:
	   print ("not much chance (0) of a storm")
	elif prob == 5:
	   print ("Minimal (5) storm detected")
	elif prob == 20:
	   print ("Minimal (20) storm detected")
	elif prob == 30:
	   print ("Storm (30) detected")
        elif prob == 60:
           print ("Storm approaching")
        elif prob == 90:
           print ("Storm close by!")
        elif prob == 95:
           print ("Storm right here!")
        elif prob == 100:
           print ("Storm is on top - shutdown!")
	   outf = open("check.log","a")
	   outf.write(time.strftime(" %Y/%m/%d"))
	   outf.write(time.strftime(" %H:%M:%S"))
	   outf.write("  -  Storm is on top - shutdown!\n")
#	   outf.write(myURL)
#	   outf.write("\n")
	   outf.flush()
	   outf.close()

	   check_call(['/usr/bin/curl', myURL])
	   # if we are shutting down, wait a few minutes
	   # do not resend the shutdown command

	   print("Sleeping for 5 minutes if in test mode")
	   time.sleep(300)
	time.sleep(mySleep)
