#!/bin/bash

echo 'playing no storm' 
./MQTTplayer 1
echo 'sleeping for 30'
sleep 30
echo 'playing storm'
./MQTTplayer 2
echo 'sleeping for 30'
sleep 30
echo 'playing storm recedes'
./MQTTplayer 3
sleep 30
echo 'playing after storm '
./MQTTplayer 4

